## create user aman
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "admin1",
    "email": "pemiliktoko@gmail.com",
    "password": "pemiliktoko"
}

### read users aman
GET http://localhost:5000/users

### update user aman
PATCH http://localhost:5000/user/146aa0ae-b384-4716-9c4b-19017eb3339d
Content-Type: application/json

{
    "name": "Kasir001",
    "email": "Kasir01@gmail.com"
}

###
// delete user aman
DELETE http://localhost:5000/user/a123ddab-fa6a-4548-aa1a-a185c5c29bdf
Content-Type: application/json

###
// login user aman
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "kasir@gmail.com",
    "password": "kasir",
    "role": "kasir"
}

###
// login user 401 terus
GET  http://localhost:5000/me
Content-Type: application/json


###
// create kategori aman
POST http://localhost:5000/kategoris
Content-Type: application/json

{
    "nama_kategori": "Barang"
}

###
// read kategori aman
GET  http://localhost:5000/kategoris/9c687aba-d370-4007-88da-1d8b252e19e6
Content-Type: application/json

###
// update kategori aman
PATCH  http://localhost:5000/kategori/dee8f2c2-324b-408a-be11-3ef19e89ada8
Content-Type: application/json

{
    "nama_kategori": "Snack"
}

###
// delete kategori aman
DELETE http://localhost:5000/kategori/dee8f2c2-324b-408a-be11-3ef19e89ada8
Content-Type:: application/json


###
// create produk aman
POST http://localhost:5000/products
Content-Type: application/json

{
    "nama_produk": "Snack Aries 800gr",
    "harga": "10000",
    "stok": "4",
    "kategoriId": "3"
}

### unkown kategori id
// read produk "Unknown column 'kategori.nama_produk' in 'field list'"
GET  http://localhost:5000/products
Content-Type: application/json

###
// update produk aman
PATCH http://localhost:5000/product/e1b4adb0-d0e1-43e0-ac96-a587a73ad077
Content-Type: application/json

{
    "nama_produk": "Kacang Garuda 3000g",
    "harga": "7000",
    "stok": "5",
    "kategoriId": "2"
}

###
// delete produk aman
DELETE http://localhost:5000/product/683de768-03d0-4fd7-8746-6ba6bddc9193
Content-Type:: application/json

###
// create penjualan aman
POST http://localhost:5000/penjualans
Content-Type: application/json

{
    "jumlah":"3",
    "produk_id":"2",
    "total_penjualan": "2"
}

###
// read penjualan aman
GET http://localhost:5000/penjualans
Content-Type: application/json

###
// update penjualan aman
PATCH http://localhost:5000/penjualan/dbca05a5-be46-4e66-9e1d-c8808e1f3c05
Content-Type: application/json

{
    "jumlah":"5",
    "produk_id":"1",
    "total_penjualan": "3"
}

###
// delete penjualan aman
DELETE http://localhost:5000/penjualan/dbca05a5-be46-4e66-9e1d-c8808e1f3c05
Content-Type: application/json

###
// create saldo login aman
POST http://localhost:5000/saldologin
Content-Type: application/json

{
    "saldo": "5000",
    "userId": "1"
}

